# Generated by Django 6.0.1 on 2026-01-27 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV')], max_length=10)),
                ('tmdb_id', models.IntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['media_type', 'tmdb_id'], name='reviews_rat_media_t_069d24_idx'), models.Index(fields=['user', 'created_at'], name='reviews_rat_user_id_d1881b_idx')],
                'unique_together': {('user', 'media_type', 'tmdb_id')},
            },
        ),
    ]
