# Generated by Django 6.0.1 on 2026-01-22 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media_type',
            field=models.CharField(choices=[('movie', 'filme'), ('tv', 'série')], default='movie', max_length=10),
        ),
        migrations.AddField(
            model_name='comment',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'media_type', 'tmdb_id')},
        ),
    ]
