"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from dotenv import load_dotenv
import logging
import os
import sys
from pathlib import Path
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "false").lower() == "true"
TESTING = "test" in sys.argv
IS_PRODUCTION = not DEBUG and not TESTING

if IS_PRODUCTION and SECRET_KEY == "change-me":
    raise ImproperlyConfigured("SECRET_KEY must be configured in production.")

if DEBUG or TESTING:
    ALLOWED_HOSTS = ["*"]
else:
    env_hosts = [h for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h]
    if not env_hosts:
        raise ImproperlyConfigured("ALLOWED_HOSTS must be configured in production.")
    ALLOWED_HOSTS = env_hosts

if DEBUG or TESTING:
    CSRF_TRUSTED_ORIGINS = []
else:
    env_csrf = [o for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o]
    CSRF_TRUSTED_ORIGINS = env_csrf


def _admin_url_from_env() -> str:
    value = os.getenv("ADMIN_URL", "admin/" if DEBUG or TESTING else "").strip()
    if not value:
        raise ImproperlyConfigured("ADMIN_URL must be configured in production.")
    value = value.strip("/")
    if not value:
        raise ImproperlyConfigured("ADMIN_URL cannot be empty.")
    if IS_PRODUCTION and value.lower() == "admin":
        raise ImproperlyConfigured("ADMIN_URL cannot be the default 'admin/' in production.")
    return f"{value}/"


ADMIN_URL = _admin_url_from_env()
ADMIN_ALLOWED_IPS = [ip.strip() for ip in os.getenv("ADMIN_ALLOWED_IPS", "").split(",") if ip.strip()]
ADMIN_TRUST_X_FORWARDED_FOR = os.getenv("ADMIN_TRUST_X_FORWARDED_FOR", "false").lower() == "true"
ADMIN_LOGIN_RATE_LIMIT = int(os.getenv("ADMIN_LOGIN_RATE_LIMIT", "5"))
ADMIN_LOGIN_RATE_TIMEOUT = int(os.getenv("ADMIN_LOGIN_RATE_TIMEOUT", str(60 * 15)))
SECURITY_CSP_ENABLED = os.getenv("SECURITY_CSP_ENABLED", "true").lower() == "true"
SECURITY_CSP_REPORT_ONLY = os.getenv("SECURITY_CSP_REPORT_ONLY", "false").lower() == "true"
MAGIC_LINK_TOKEN_TIMEOUT = int(os.getenv("MAGIC_LINK_TOKEN_TIMEOUT", str(60 * 15)))
MAGIC_LINK_REQUEST_LIMIT = int(os.getenv("MAGIC_LINK_REQUEST_LIMIT", "5"))
MAGIC_LINK_REQUEST_TIMEOUT = int(os.getenv("MAGIC_LINK_REQUEST_TIMEOUT", str(60 * 15)))
EMAIL_CONFIRMATION_RESEND_LIMIT = int(os.getenv("EMAIL_CONFIRMATION_RESEND_LIMIT", "5"))
EMAIL_CONFIRMATION_RESEND_TIMEOUT = int(os.getenv("EMAIL_CONFIRMATION_RESEND_TIMEOUT", str(60 * 15)))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    
    'core.apps.CoreConfig',
    'accounts.apps.AccountsConfig',
    'movies',
    'comments',
    'reviews',
    'favorites',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.RequestIdMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.AdminSecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'core.middleware.RequestLogMiddleware',
    'core.middleware.PrivateNoStoreMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'



# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
if IS_PRODUCTION and not DATABASE_URL:
    raise ImproperlyConfigured("DATABASE_URL must be configured in production.")

DATABASES = {
    "default": dj_database_url.config(
        default=DATABASE_URL or f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=int(os.getenv("DB_CONN_MAX_AGE", "60" if IS_PRODUCTION else "0")),
    )
}

DATABASE_BACKUP_DIR = os.getenv("DATABASE_BACKUP_DIR", str(BASE_DIR / "backups" / "database"))


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

SITE_ID = 1

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = int(os.getenv("ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS", "3"))
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_SIGNUP_FORM_HONEYPOT_FIELD = "phone_number"
ACCOUNT_PREVENT_ENUMERATION = "strict"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Ludarius] "
ACCOUNT_RATE_LIMITS = {
    "signup": "5/h/ip",
    "login": "30/m/ip",
    "login_failed": "10/m/ip,5/5m/key",
    "confirm_email": "1/3m/key",
    "reset_password": "10/h/ip,5/h/key",
}

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
}

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@ludarius.local")
EMAIL_FILE_PATH = os.getenv("EMAIL_FILE_PATH", str(BASE_DIR / "tmp" / "emails"))
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    (
        "django.core.mail.backends.filebased.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_PROVIDER = os.getenv("EMAIL_PROVIDER", "smtp").strip().lower()
EMAIL_PROVIDER_DEFAULTS = {
    "smtp": {"host": "localhost", "port": 25, "tls": False, "ssl": False},
    "gmail": {"host": "smtp.gmail.com", "port": 587, "tls": True, "ssl": False},
    "resend": {"host": "smtp.resend.com", "port": 587, "tls": True, "ssl": False},
    "brevo": {"host": "smtp-relay.brevo.com", "port": 587, "tls": True, "ssl": False},
}
if EMAIL_PROVIDER not in EMAIL_PROVIDER_DEFAULTS:
    raise ImproperlyConfigured("EMAIL_PROVIDER must be one of: smtp, gmail, resend, brevo.")
EMAIL_DEFAULTS = EMAIL_PROVIDER_DEFAULTS[EMAIL_PROVIDER]
EMAIL_HOST = os.getenv("EMAIL_HOST", EMAIL_DEFAULTS["host"])
EMAIL_PORT = int(os.getenv("EMAIL_PORT", str(EMAIL_DEFAULTS["port"])))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", str(EMAIL_DEFAULTS["tls"]).lower()).lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", str(EMAIL_DEFAULTS["ssl"]).lower()).lower() == "true"
EMAIL_REQUIRE_AUTH = os.getenv("EMAIL_REQUIRE_AUTH", "true" if IS_PRODUCTION else "false").lower() == "true"

if IS_PRODUCTION:
    if EMAIL_BACKEND == "django.core.mail.backends.console.EmailBackend":
        raise ImproperlyConfigured("EMAIL_BACKEND must not use console backend in production.")
    if EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend" and not EMAIL_HOST:
        raise ImproperlyConfigured("EMAIL_HOST must be configured in production.")
    if EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend" and EMAIL_REQUIRE_AUTH:
        if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
            raise ImproperlyConfigured("EMAIL_HOST_USER and EMAIL_HOST_PASSWORD must be configured in production.")
    if DEFAULT_FROM_EMAIL.endswith(".local"):
        raise ImproperlyConfigured("DEFAULT_FROM_EMAIL must be configured in production.")


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_BACKEND = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if TESTING
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

STORAGES = {
    "staticfiles": {
        "BACKEND": STATICFILES_BACKEND,
    }
}

TMDB_API_KEY = os.getenv('TMDB_API_KEY')

REDIS_URL = os.getenv("REDIS_URL", "").strip()
if IS_PRODUCTION and not REDIS_URL:
    raise ImproperlyConfigured("REDIS_URL must be configured in production for shared rate limits and magic links.")

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "KEY_PREFIX": os.getenv("CACHE_KEY_PREFIX", "ludarius"),
        }
    }
else:
    CACHE_BACKEND = os.getenv("CACHE_BACKEND", "django.core.cache.backends.locmem.LocMemCache")
    CACHE_LOCATION = os.getenv("CACHE_LOCATION", "ludarius-cache")
    CACHES = {
        "default": {
            "BACKEND": CACHE_BACKEND,
            "LOCATION": CACHE_LOCATION,
        }
    }

# Security (prod)
SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "false").lower() == "true"

if IS_PRODUCTION:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000" if SECURE_SSL_REDIRECT else "0"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS",
        "true" if SECURE_HSTS_SECONDS else "false",
    ).lower() == "true"
    SECURE_HSTS_PRELOAD = os.getenv(
        "SECURE_HSTS_PRELOAD",
        "true" if SECURE_HSTS_SECONDS else "false",
    ).lower() == "true"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

SENTRY_DSN = os.getenv("SENTRY_DSN", "").strip()
SENTRY_ENVIRONMENT = os.getenv("SENTRY_ENVIRONMENT", "development" if DEBUG else "production")
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.0"))
SENTRY_SEND_DEFAULT_PII = os.getenv("SENTRY_SEND_DEFAULT_PII", "false").lower() == "true"
RELEASE_VERSION = os.getenv("RELEASE_VERSION", "").strip()

if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.logging import LoggingIntegration
    except ImportError as exc:
        raise ImproperlyConfigured("sentry-sdk must be installed when SENTRY_DSN is configured.") from exc

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            LoggingIntegration(level=logging.INFO, event_level=logging.ERROR),
        ],
        environment=SENTRY_ENVIRONMENT,
        release=RELEASE_VERSION or None,
        send_default_pii=SENTRY_SEND_DEFAULT_PII,
        traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
    )

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {
            "()": "core.logging.RequestIdFilter",
        },
    },
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s [%(name)s] [request_id=%(request_id)s] %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["request_id"],
            "formatter": "standard",
        }
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "security.audit": {
            "handlers": ["console"],
            "level": os.getenv("SECURITY_AUDIT_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "core.requests": {
            "handlers": ["console"],
            "level": os.getenv("REQUEST_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}
